spring:
  h2:
    console:
      enabled=true:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/boosterdb
##    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#    username: admin
#    password:
    datasource:
      url: ${DB_URL}
      username: ${USERNAME}
      password: ${PASSWORD}
      platform: postgres